# Generated by Django 5.2 on 2025-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
