# Generated by Django 5.2 on 2025-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_reader', '0002_feeditem_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='guid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='feeditem',
            unique_together={('feed', 'guid')},
        ),
    ]
